### ISSUE TITLE
When I run  fault_diagnosis.py, I meet the following problem, ask for the solution, thank you. 

### ISSUE THREAD

**Issue by gaoyacui** [hezheug/vibration_gan#1]
D:\anaconda\envs\tensorflow1.14\python.exe D:/daima/gan/vibration_gan-master/vibration_gan-master/fault_diagnosis.py
Using TensorFlow backend.
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda\envs\tensorflow1.14\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
训练样本维度: (5000, 896, 1)
5000 训练样本个数
验证样本的维度 (2500, 896, 1)
2500 验证样本个数
测试样本的维度 (2500, 896, 1)
2500 测试样本个数
WARNING:tensorflow:From D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\backend\tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\backend\tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Traceback (most recent call last):
  File "D:/daima/gan/vibration_gan-master/vibration_gan-master/fault_diagnosis.py", line 130, in <module>
    model.load_weights('diagnosis_CWRU_model/order-50-0.71-best.hdf5')
  File "D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "D:\anaconda\envs\tensorflow1.14\lib\site-packages\keras\engine\network.py", line 1208, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "D:\anaconda\envs\tensorflow1.14\lib\site-packages\h5py\_hl\files.py", line 427, in __init__
    swmr=swmr)
  File "D:\anaconda\envs\tensorflow1.14\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'diagnosis_CWRU_model/order-50-0.71-best.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Process finished with exit code 1

**Comment by he-zh** [comment]
Please set Test = False in line 113, fault_diagnosis.py

**Comment by gaoyacui** [comment]
> 请在第113行fault_diagnosis.py中设置Test = False。

Thank you very much for your reply. My code has this sentence on line 113.It still can't run successfully.Could you tell me what caused it?

![Uploading image.png…]()

**Comment by gaoyacui** [comment]
![image](https://user-images.githubusercontent.com/68311760/108626650-43670300-748c-11eb-8425-f14d6054cc3a.png)

**Comment by he-zh** [comment]
I have updated files of fault_diagnoisis.py and train_gan.py, would you please try it again according to the guidance on repository homepage?

**Comment by gaoyacui** [comment]
Trying again, thank you

**Comment by gaoyacui** [comment]
When I run diagnosis_test.py, I meet the following problem1.At the same time,when I run loss_display.py,meet  the following problem2 ,ask for the solution, thank you.

1.  OSError: Unable to open file (unable to open file: name = 'diagnosis_CWRU_model/none-order-1-best.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2. FileNotFoundError: [Errno 2] No such file or directory: 'samples\\WGAN-GP\\ORDER\\ratio-50\\orderOR021-05-17-20_23\\w-ratio50-order-minmax-OR021_98331.out'
