### ISSUE TITLE
generate target signals with pretrained gan: $ python train_gan.py --phase='generate' --checkpoint_dir=which-pretrained-model-in-checkpoint-dir --target='B007'

### ISSUE THREAD

**Issue by gaoyacui** [hezheug/vibration_gan#3]
Sorry to bother you again.
When i changed 'train' to ‘generate',and the '--checkpoint_dir=which-pretrained-model-in-checkpoint-dir' becomed 'parser.add_argument('--checkpoint_dir', type=str, default='samples\WGAN-GP\ORDER\ratio-50\orderB007-05-17-20_22\checkpoint\model-97000', help='the saved checkpoint to generate signals')',but i meet the error :UnboundLocalError: local variable 'samples_dir' referenced before assignment.Is it the problem that I modified?
At the same time, I really won't change it'--checkpoint_dir=which-pretrained-model-in-checkpoint-dir'.

**Comment by ssslxr** [comment]
> 
> 
> Sorry to bother you again. When i changed 'train' to ‘generate',and the '--checkpoint_dir=which-pretrained-model-in-checkpoint-dir' becomed 'parser.add_argument('--checkpoint_dir', type=str, default='samples\WGAN-GP\ORDER\ratio-50\orderB007-05-17-20_22\checkpoint\model-97000', help='the saved checkpoint to generate signals')',but i meet the error :UnboundLocalError: local variable 'samples_dir' referenced before assignment.Is it the problem that I modified? At the same time, I really won't change it'--checkpoint_dir=which-pretrained-model-in-checkpoint-dir'.

请问你会了么？

**Comment by he-zh** [comment]
Sorry for the late reply, I fix this bug by modifying the [make_dir() function](https://github.com/hezheug/vibration_gan/blob/master/train_gan.py#L156). It should be fine now.
